"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 22:06:11.050680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### H2-10 manual: funciones propias (autogenerate no las detecta) ###
    # uuidv7(): Supabase corre PG17 sin uuidv7() nativo (era PG18 en H2-01).
    # Se crea como funcion SQL propia con pgcrypto para no tocar los 14 modelos.
    op.execute(sa.text("""CREATE OR REPLACE FUNCTION public.uuidv7() RETURNS uuid
LANGUAGE plpgsql VOLATILE PARALLEL SAFE AS $func$
DECLARE
  b bytea := gen_random_bytes(16);
BEGIN
  b := set_byte(b, 6, (get_byte(b, 6) & 15) | 112);
  b := set_byte(b, 8, (get_byte(b, 8) & 63) | 128);
  RETURN encode(b, 'hex')::uuid;
END
$func$;"""))
    op.execute(sa.text("""CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $func$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END
$func$;"""))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_ref',
    sa.Column('claim_id', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('claim_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('conversation',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('anonymous_sid', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('title_search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('spanish', coalesce(title, ''))", persisted=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(context) = 'object'", name='ck_conversation_context_object'),
    sa.CheckConstraint("status IN ('ACTIVE','ARCHIVED','CLOSED')", name='ck_conversation_status'),
    sa.CheckConstraint('char_length(title) <= 40', name='ck_conversation_title_length'),
    sa.CheckConstraint('customer_id IS NOT NULL OR anonymous_sid IS NOT NULL', name='ck_conversation_owner'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_active_last_message', 'conversation', ['last_message_at'], unique=False, postgresql_where=sa.text("status = 'ACTIVE' AND customer_id IS NOT NULL"))
    op.create_index('ix_conversation_anonymous_last_message', 'conversation', ['last_message_at'], unique=False, postgresql_where=sa.text('customer_id IS NULL'))
    op.create_index('ix_conversation_anonymous_sid', 'conversation', ['anonymous_sid'], unique=False, postgresql_where=sa.text('customer_id IS NULL'))
    op.create_index('ix_conversation_customer_last_message', 'conversation', ['customer_id', sa.text('last_message_at DESC')], unique=False, postgresql_where=sa.text('title IS NOT NULL'))
    op.create_index('ix_conversation_title_search_vector', 'conversation', ['title_search_vector'], unique=False, postgresql_using='gin')
    op.create_table('local_phone_verification',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("phone ~ '^\\+51[0-9]{9}$'", name='ck_local_phone_verification_format'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'phone', name='uq_local_phone_verification_customer_phone')
    )
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name='ck_outbox_payload_object'),
    sa.CheckConstraint("status IN ('PENDING','PROCESSED','FAILED')", name='ck_outbox_status'),
    sa.CheckConstraint("type IN ('NOTIFY_SALES_PAYMENT','REQUEST_CANCELLATION','SEND_EMAIL')", name='ck_outbox_type'),
    sa.CheckConstraint('attempts BETWEEN 0 AND 5', name='ck_outbox_attempts'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbox_failed_created_at', 'outbox', [sa.text('created_at DESC')], unique=False, postgresql_where=sa.text("status = 'FAILED'"))
    op.create_index('ix_outbox_next_attempt_at', 'outbox', ['next_attempt_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('return_ref',
    sa.Column('return_id', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('requested_type', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("requested_type IN ('EXCHANGE','MONEY_REFUND')", name='ck_return_ref_requested_type'),
    sa.PrimaryKeyConstraint('return_id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('cart',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('coupon_code', sa.Text(), nullable=True),
    sa.Column('address_id', sa.UUID(), nullable=True),
    sa.Column('shipping_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('totals_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(shipping_snapshot) = 'object'", name='ck_cart_shipping_snapshot_object'),
    sa.CheckConstraint("jsonb_typeof(totals_snapshot) = 'object'", name='ck_cart_totals_snapshot_object'),
    sa.CheckConstraint("status IN ('ACTIVE','IN_CHECKOUT','CONVERTED','ABANDONED','MERGED')", name='ck_cart_status'),
    sa.CheckConstraint('customer_id IS NOT NULL OR conversation_id IS NOT NULL', name='ck_cart_owner'),
    sa.CheckConstraint('version >= 0', name='ck_cart_version'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cart_anonymous_updated_at', 'cart', ['updated_at'], unique=False, postgresql_where=sa.text("customer_id IS NULL AND status = 'ACTIVE'"))
    op.create_index('ix_cart_conversation_id', 'cart', ['conversation_id'], unique=False)
    op.create_index('uq_cart_conversation_open', 'cart', ['conversation_id'], unique=True, postgresql_where=sa.text("customer_id IS NULL AND status IN ('ACTIVE','IN_CHECKOUT')"))
    op.create_index('uq_cart_customer_open', 'cart', ['customer_id'], unique=True, postgresql_where=sa.text("status IN ('ACTIVE','IN_CHECKOUT')"))
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('return_id', sa.Text(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('original_file_name', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('size_bytes BETWEEN 1 AND 5242880', name='ck_evidence_size_bytes'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['return_id'], ['return_ref.return_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_conversation_id', 'evidence', ['conversation_id'], unique=False)
    op.create_index('ix_evidence_draft', 'evidence', ['conversation_id', 'created_at'], unique=False, postgresql_where=sa.text('return_id IS NULL'))
    op.create_index('ix_evidence_return_id', 'evidence', ['return_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('blocks', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('arguments', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('result_code', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('spanish', coalesce(content, ''))", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(arguments) = 'object'", name='ck_message_arguments_object'),
    sa.CheckConstraint("jsonb_typeof(blocks) = 'object'", name='ck_message_blocks_object'),
    sa.CheckConstraint("role <> 'TOOL' OR tool_name IS NOT NULL", name='ck_message_tool_name'),
    sa.CheckConstraint("role IN ('CUSTOMER','ASSISTANT','TOOL')", name='ck_message_role'),
    sa.CheckConstraint('input_tokens >= 0', name='ck_message_input_tokens'),
    sa.CheckConstraint('latency_ms >= 0', name='ck_message_latency'),
    sa.CheckConstraint('output_tokens >= 0', name='ck_message_output_tokens'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_conversation_created_at', 'message', ['conversation_id', sa.text('created_at DESC')], unique=False)
    op.create_index('ix_message_search_vector', 'message', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('attachment',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('thumbnail_key', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'SENT') = (message_id IS NOT NULL)", name='ck_attachment_status_message'),
    sa.CheckConstraint("mime_type IN ('image/jpeg','image/png','image/webp')", name='ck_attachment_mime_type'),
    sa.CheckConstraint("status IN ('PENDING','SENT')", name='ck_attachment_status'),
    sa.CheckConstraint('height > 0', name='ck_attachment_height'),
    sa.CheckConstraint('size_bytes BETWEEN 1 AND 5242880', name='ck_attachment_size_bytes'),
    sa.CheckConstraint('width > 0', name='ck_attachment_width'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key', name='uq_attachment_storage_key'),
    sa.UniqueConstraint('thumbnail_key', name='uq_attachment_thumbnail_key')
    )
    op.create_index('ix_attachment_conversation_status', 'attachment', ['conversation_id', 'status'], unique=False)
    op.create_index('ix_attachment_message_id', 'attachment', ['message_id'], unique=False, postgresql_where=sa.text('message_id IS NOT NULL'))
    op.create_index('ix_attachment_pending_created_at', 'attachment', ['created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('cart_item',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('variant_description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_ref', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity BETWEEN 1 AND 10', name='ck_cart_item_quantity'),
    sa.CheckConstraint('unit_price_ref >= 0', name='ck_cart_item_unit_price_ref'),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'sku', name='uq_cart_item_cart_sku')
    )
    op.create_index('ix_cart_item_cart_id', 'cart_item', ['cart_id'], unique=False)
    op.create_table('checkout',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'PENDING_PAYMENT'"), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(summary) = 'object'", name='ck_checkout_summary_object'),
    sa.CheckConstraint("status IN ('PENDING_PAYMENT','PAYMENT_APPROVED','CONFIRMED','FAILED','EXPIRED')", name='ck_checkout_status'),
    sa.CheckConstraint('payment_attempts BETWEEN 0 AND 3', name='ck_checkout_payment_attempts'),
    sa.CheckConstraint('total >= 0', name='ck_checkout_total'),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_checkout_cart_id', 'checkout', ['cart_id'], unique=False)
    op.create_index('ix_checkout_expires_at', 'checkout', ['expires_at'], unique=False, postgresql_where=sa.text("status = 'PENDING_PAYMENT'"))
    op.create_index('uq_checkout_cart_alive', 'checkout', ['cart_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING_PAYMENT','PAYMENT_APPROVED')"))
    op.create_index('uq_checkout_idempotency_key', 'checkout', ['idempotency_key'], unique=True)
    op.create_table('order_ref',
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('checkout_id', sa.UUID(), nullable=False),
    sa.Column('local_status', sa.Text(), server_default=sa.text("'CREATED'"), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("local_status IN ('CREATED','PAYMENT_PENDING_NOTIFICATION','PAID_NOTIFIED','CANCELLATION_REQUESTED','CANCELLED')", name='ck_order_ref_local_status'),
    sa.CheckConstraint('total >= 0', name='ck_order_ref_total'),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('order_id'),
    sa.UniqueConstraint('checkout_id', name='uq_order_ref_checkout_id')
    )
    op.create_index('ix_order_ref_checkout_id', 'order_ref', ['checkout_id'], unique=False)
    op.create_index('ix_order_ref_customer_id', 'order_ref', ['customer_id'], unique=False)
    op.create_table('payment_attempt',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('checkout_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('transaction_id', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('last4', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(result = 'APPROVED') = (reason IS NULL)", name='ck_payment_attempt_result_reason'),
    sa.CheckConstraint("brand IN ('VISA','MASTERCARD','AMEX')", name='ck_payment_attempt_brand'),
    sa.CheckConstraint("last4 ~ '^[0-9]{4}$'", name='ck_payment_attempt_last4'),
    sa.CheckConstraint("reason IN ('INSUFFICIENT_FUNDS','DECLINED_BY_ISSUER','PROCESSING_ERROR','INVALID_DATA')", name='ck_payment_attempt_reason'),
    sa.CheckConstraint("result IN ('APPROVED','REJECTED','ERROR')", name='ck_payment_attempt_result'),
    sa.CheckConstraint('amount > 0', name='ck_payment_attempt_amount'),
    sa.ForeignKeyConstraint(['checkout_id'], ['checkout.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index('ix_payment_attempt_checkout_id', 'payment_attempt', ['checkout_id'], unique=False)
    op.create_index('uq_payment_attempt_idempotency_key', 'payment_attempt', ['idempotency_key'], unique=True)
    op.create_table('notification',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('order_id', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('resend_number', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(type = 'ORDER_CONFIRMATION' AND resend_number = 0) OR (type = 'CONFIRMATION_RESEND' AND resend_number IN (1, 2))", name='ck_notification_type_resend'),
    sa.CheckConstraint("status IN ('PENDING','SENT','FAILED')", name='ck_notification_status'),
    sa.CheckConstraint("type IN ('ORDER_CONFIRMATION','CONFIRMATION_RESEND')", name='ck_notification_type'),
    sa.CheckConstraint('attempts BETWEEN 0 AND 3', name='ck_notification_attempts'),
    sa.ForeignKeyConstraint(['order_id'], ['order_ref.order_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'resend_number', name='uq_notification_order_resend')
    )
    op.create_index('ix_notification_order_id', 'notification', ['order_id'], unique=False)
    # ### H2-10 manual: triggers updated_at (autogenerate no los detecta) ###
    for _table in ('attachment', 'cart', 'cart_item', 'checkout', 'conversation',
                   'evidence', 'notification', 'order_ref', 'outbox'):
        op.execute(sa.text(
            f"CREATE TRIGGER trg_{_table}_updated_at BEFORE UPDATE ON {_table} "
            "FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();"
        ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### H2-10 manual: baja triggers antes de tumbar tablas ###
    for _table in ('attachment', 'cart', 'cart_item', 'checkout', 'conversation',
                   'evidence', 'notification', 'order_ref', 'outbox'):
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS trg_{_table}_updated_at ON {_table};"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_order_id', table_name='notification')
    op.drop_table('notification')
    op.drop_index('uq_payment_attempt_idempotency_key', table_name='payment_attempt')
    op.drop_index('ix_payment_attempt_checkout_id', table_name='payment_attempt')
    op.drop_table('payment_attempt')
    op.drop_index('ix_order_ref_customer_id', table_name='order_ref')
    op.drop_index('ix_order_ref_checkout_id', table_name='order_ref')
    op.drop_table('order_ref')
    op.drop_index('uq_checkout_idempotency_key', table_name='checkout')
    op.drop_index('uq_checkout_cart_alive', table_name='checkout', postgresql_where=sa.text("status IN ('PENDING_PAYMENT','PAYMENT_APPROVED')"))
    op.drop_index('ix_checkout_expires_at', table_name='checkout', postgresql_where=sa.text("status = 'PENDING_PAYMENT'"))
    op.drop_index('ix_checkout_cart_id', table_name='checkout')
    op.drop_table('checkout')
    op.drop_index('ix_cart_item_cart_id', table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index('ix_attachment_pending_created_at', table_name='attachment', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_attachment_message_id', table_name='attachment', postgresql_where=sa.text('message_id IS NOT NULL'))
    op.drop_index('ix_attachment_conversation_status', table_name='attachment')
    op.drop_table('attachment')
    op.drop_index('ix_message_search_vector', table_name='message', postgresql_using='gin')
    op.drop_index('ix_message_conversation_created_at', table_name='message')
    op.drop_table('message')
    op.drop_index('ix_evidence_return_id', table_name='evidence')
    op.drop_index('ix_evidence_draft', table_name='evidence', postgresql_where=sa.text('return_id IS NULL'))
    op.drop_index('ix_evidence_conversation_id', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('uq_cart_customer_open', table_name='cart', postgresql_where=sa.text("status IN ('ACTIVE','IN_CHECKOUT')"))
    op.drop_index('uq_cart_conversation_open', table_name='cart', postgresql_where=sa.text("customer_id IS NULL AND status IN ('ACTIVE','IN_CHECKOUT')"))
    op.drop_index('ix_cart_conversation_id', table_name='cart')
    op.drop_index('ix_cart_anonymous_updated_at', table_name='cart', postgresql_where=sa.text("customer_id IS NULL AND status = 'ACTIVE'"))
    op.drop_table('cart')
    op.drop_table('return_ref')
    op.drop_index('ix_outbox_next_attempt_at', table_name='outbox', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index('ix_outbox_failed_created_at', table_name='outbox', postgresql_where=sa.text("status = 'FAILED'"))
    op.drop_table('outbox')
    op.drop_table('local_phone_verification')
    op.drop_index('ix_conversation_title_search_vector', table_name='conversation', postgresql_using='gin')
    op.drop_index('ix_conversation_customer_last_message', table_name='conversation', postgresql_where=sa.text('title IS NOT NULL'))
    op.drop_index('ix_conversation_anonymous_sid', table_name='conversation', postgresql_where=sa.text('customer_id IS NULL'))
    op.drop_index('ix_conversation_anonymous_last_message', table_name='conversation', postgresql_where=sa.text('customer_id IS NULL'))
    op.drop_index('ix_conversation_active_last_message', table_name='conversation', postgresql_where=sa.text("status = 'ACTIVE' AND customer_id IS NOT NULL"))
    op.drop_table('conversation')
    op.drop_table('claim_ref')
    # ### H2-10 manual: baja funciones propias al final ###
    op.execute(sa.text("DROP FUNCTION IF EXISTS public.set_updated_at();"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS public.uuidv7();"))
    # ### end Alembic commands ###
